
SELECT USER FROM DUAL;


-- ==TABLA PACIENTE==--
CREATE TABLE PACIENTE (
  rut_paciente  VARCHAR2(10) PRIMARY KEY,
  dv_paciente   CHAR(1)       NOT NULL,
  nombres       VARCHAR2(25)  NOT NULL,
  papellido     VARCHAR2(25)  NOT NULL,
  sapellido     VARCHAR2(25),
  fecha_nac     DATE,
  telefono      VARCHAR2(15) UNIQUE,
  direccion     VARCHAR2(50),
  comuna        VARCHAR2(25),
  region        VARCHAR2(25)
);
    
    
    
--==TABLA DIAGNOSTICO==--
CREATE TABLE DIAGNOSTICO (
    cod_diagnostico NUMBER(7) PRIMARY KEY,
    nombre          VARCHAR2(25) NOT NULL UNIQUE
);



--==TABLA MEDICAMENTO==--
CREATE TABLE MEDICAMENTO(
  cod_medicamento  NUMBER(7)   PRIMARY KEY,
  nombre           VARCHAR2(25) NOT NULL,
  tipo_medicamento VARCHAR2(25) NOT NULL,
  via_administra   VARCHAR2(20)
);



--==TABLA MEDICO==--
CREATE TABLE MEDICO(
  rut_medico   VARCHAR2(9)  PRIMARY KEY,
  dv_medico    CHAR(1)      NOT NULL,
  nombres      VARCHAR2(25) NOT NULL,
  papellido    VARCHAR2(25) NOT NULL,
  sapellido    VARCHAR2(25),
  especialidad VARCHAR2(25)
);



--==TABLA DIGITADOR==--
CREATE TABLE DIGITADOR(
  id_digitador NUMBER        PRIMARY KEY,
  nombres      VARCHAR2(25)  NOT NULL,
  papellido    VARCHAR2(25)  NOT NULL
);



--==TABLA TIPO_RECETA==--
CREATE TABLE TIPO_RECETA(
  id_tipo_receta NUMBER(3)   PRIMARY KEY,
  nombre         VARCHAR2(25) NOT NULL UNIQUE
);



--==TABLA RECETA==--
CREATE TABLE RECETA(
  cod_receta        NUMBER(7)   PRIMARY KEY,
  observacion       VARCHAR2(500),
  fecha_emision     DATE        NOT NULL,
  fecha_vencimiento DATE,
  id_digitador      NUMBER      NOT NULL,
  rut_paciente      VARCHAR2(10) NOT NULL,
  rut_medico        VARCHAR2(9)  NOT NULL,
  id_diagnostico    NUMBER(7)    NOT NULL,
  tipo_receta       NUMBER(3)    NOT NULL,
  CONSTRAINT fk_receta_digitador   FOREIGN KEY (id_digitador)   REFERENCES DIGITADOR(id_digitador),
  CONSTRAINT fk_receta_paciente    FOREIGN KEY (rut_paciente)   REFERENCES PACIENTE(rut_paciente),
  CONSTRAINT fk_receta_diagnostico FOREIGN KEY (id_diagnostico) REFERENCES DIAGNOSTICO (cod_diagnostico),
  CONSTRAINT fk_receta_medico      FOREIGN KEY (rut_medico)     REFERENCES MEDICO (rut_medico),
  CONSTRAINT fk_receta_tiporec     FOREIGN KEY (tipo_receta)    REFERENCES TIPO_RECETA (id_tipo_receta)
);



--==TABLA BANCO==--
CREATE TABLE BANCO(
  cod_banco NUMBER(2)     PRIMARY KEY,
  nombre    VARCHAR2(25)  NOT NULL UNIQUE
);



--==TABLA PAGO==--
CREATE TABLE PAGO(
  cod_boleta  NUMBER(6)    PRIMARY KEY,
  cod_receta  NUMBER(7)    NOT NULL,
  fecha_pago  DATE         NOT NULL,
  monto_total NUMBER(10)   NOT NULL,
  metodo_pago VARCHAR2(15) NOT NULL,
  id_banco    NUMBER(2),
  CONSTRAINT fk_pago_receta FOREIGN KEY (cod_receta) REFERENCES RECETA (cod_receta),
  CONSTRAINT fk_pago_banco  FOREIGN KEY (id_banco)   REFERENCES BANCO (cod_banco)
);



--==TABLA DOSIS==--
CREATE TABLE DOSIS(
  cod_medicamento   NUMBER(7)    NOT NULL,
  cod_receta        NUMBER(7)    NOT NULL,
  descripcion_dosis VARCHAR2(50) NOT NULL,
  CONSTRAINT pk_dosis       PRIMARY KEY (cod_medicamento, cod_receta),
  CONSTRAINT fk_dosis_medic FOREIGN KEY (cod_medicamento) REFERENCES MEDICAMENTO (cod_medicamento),
  CONSTRAINT fk_dosis_rec   FOREIGN KEY (cod_receta)      REFERENCES RECETA (cod_receta)
);

SELECT table_name FROM user_tables ORDER BY 1;

SELECT constraint_name, table_name, constraint_type
FROM user_constraints
WHERE constraint_type IN ('P','R','U')
ORDER BY table_name, constraint_type;



--==TABLA ESPECIALIDAD==--
CREATE TABLE ESPECIALIDAD(
    id_especialidad NUMBER GENERATED ALWAYS AS IDENTITY,
    nombre          VARCHAR2(25),
    CONSTRAINT pk_especialidad PRIMARY KEY (id_especialidad),
    CONSTRAINT uq_especialidad UNIQUE (nombre)

);

--------=======FASE 2======------

INSERT INTO ESPECIALIDAD (nombre)
SELECT DISTINCT especialidad
FROM MEDICO
WHERE especialidad IS NOT NULL;



ALTER TABLE MEDICO ADD (id_especialidad NUMBER);
ALTER TABLE MEDICO DROP COLUMN especialidad;



ALTER TABLE MEDICAMENTO
    ADD (precio_unitario NUMBER(10,0));
    
    
    
    
AlTER TABLE MEDICAMENTO
    ADD CONSTRAINT ck_medicamento_precio
    CHECK (precio_unitario BETWEEN 1000 AND 2000000);
    
    
    
    
ALTER TABLE PAGO
    ADD CONSTRAINT ck_pago_metodo
    CHECK (metodo_pago IN ('EFECTIVO','TARJETA','TRANSFERENCIA'));



CREATE INDEX ix_medico_id_especialidad ON MEDICO(id_especialidad);




CREATE TABLE REGION(
    id_region      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE          VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_region PRIMARY KEY (id_region),
    CONSTRAINT uq_region_nombre UNIQUE (nombre)
);




CREATE TABLE COMUNA(
    id_comuna       NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1101 INCREMENT BY 1),
    nombre          VARCHAR2(20) NOT NULL,
    id_region       NUMBER NOT NULL,
    CONSTRAINT pk_comuna PRIMARY KEY (id_comuna),
    CONSTRAINT uq_comuna_nombre UNIQUE (nombre),
    CONSTRAINT fk_comuna_region FOREIGN KEY (id_region) REFERENCES REGION (id_region)
);




ALTER TABLE PACIENTE ADD (id_comuna NUMBER);
ALTER TABLE PACIENTE
    ADD CONSTRAINT fk_paciente_comuna FOREIGN KEY (id_comuna) REFERENCES COMUNA (id_comuna);
    
ALTER TABLE PACIENTE DROP COLUMN comuna;
ALTER TABLE PACIENTE DROP COLUMN region;
